from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.enums import TA_CENTER
from io import BytesIO
from datetime import datetime, timedelta
from typing import List, Dict


def generate_weekly_report(
    patient_name: str,
    patient_id: str,
    week_start: str,
    sessions: List[Dict],
    is_current_week: bool = False,
) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "Title", parent=styles["Title"],
        fontSize=20, textColor=colors.HexColor("#1e40af"), alignment=TA_CENTER
    )
    heading_style = ParagraphStyle(
        "Heading", parent=styles["Heading2"],
        fontSize=13, textColor=colors.HexColor("#1e40af"), spaceAfter=6
    )
    normal_style = styles["Normal"]

    week_start_dt = datetime.fromisoformat(week_start)
    week_end_dt = week_start_dt + timedelta(days=6)
    in_progress_label = " (In Progress)" if is_current_week else ""

    elements = []

    elements.append(Paragraph("SpeakBack", title_style))
    elements.append(Paragraph(f"Weekly Progress Report{in_progress_label}", styles["Heading2"]))
    elements.append(Spacer(1, 0.5*cm))

    info_data = [
        ["Patient", patient_name],
        ["Week", f"{week_start_dt.strftime('%B %d')} – {week_end_dt.strftime('%B %d, %Y')}{in_progress_label}"],
        ["Total Sessions", str(len(sessions))],
        ["Report Generated", datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")],
    ]
    info_table = Table(info_data, colWidths=[5*cm, 11*cm])
    info_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#eff6ff")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#bfdbfe")),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(info_table)
    elements.append(Spacer(1, 0.8*cm))

    if sessions:
        avg_score = sum(s.get("metric_value", 0) for s in sessions) / len(sessions)
        elements.append(Paragraph("Summary", heading_style))
        summary_data = [
            ["Average Pronunciation Score", f"{avg_score:.1f} / 100"],
            ["Sessions Completed", str(len(sessions))],
            ["Presence Detected", str(sum(1 for s in sessions if s.get("presence_detected")))],
        ]
        summary_table = Table(summary_data, colWidths=[9*cm, 7*cm])
        summary_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e40af")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#bfdbfe")),
            ("ROWBACKGROUNDS", (1, 0), (-1, -1), [colors.white, colors.HexColor("#f0f9ff")]),
            ("PADDING", (0, 0), (-1, -1), 8),
        ]))
        elements.append(summary_table)
        elements.append(Spacer(1, 0.8*cm))

        elements.append(Paragraph("Session Details", heading_style))
        session_headers = ["Date", "Exercise", "Expected", "Transcript", "Score"]
        session_rows = [session_headers]
        for s in sessions:
            ts = s.get("timestamp", "")[:10]
            session_rows.append([
                ts,
                (s.get("exercise_name") or "").replace("_", " ").title(),
                (s.get("expected_text") or "")[:25],
                (s.get("transcript") or "")[:25],
                f"{s.get('metric_value', 0):.0f}",
            ])
        session_table = Table(session_rows, colWidths=[2.5*cm, 3*cm, 4*cm, 4*cm, 2.5*cm])
        session_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e40af")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ("PADDING", (0, 0), (-1, -1), 6),
            ("ALIGN", (4, 0), (4, -1), "CENTER"),
        ]))
        elements.append(session_table)
    else:
        elements.append(Paragraph("No sessions recorded this week.", normal_style))

    elements.append(Spacer(1, 1*cm))
    elements.append(Paragraph(
        "Generated by SpeakBack — Confidential Patient Report",
        ParagraphStyle("Footer", parent=normal_style, fontSize=8,
                       textColor=colors.grey, alignment=TA_CENTER)
    ))

    doc.build(elements)
    return buffer.getvalue()
